POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoibWFya0Bkb2UuY29tIiwiaWF0IjoxNzY3NjgxOTQ1LCJleHAiOjE3Njc2ODU1NDUsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.DH9p47u1HnhR3uJPoaNqFvSOALm9q04tgkdY7zeWV9s

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImlhdCI6MTc2NzY4MTk0NSwiZXhwIjoxNzY3NzY4MzQ1LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.3Rb3BbK8QeNYrAeDCv2fy_wCAfvbNtUE9cyJTzp5LRU"
}